{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openclaw.fullname" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.credentials.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.credentials.anthropicApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.credentials.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.credentials.openaiApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
